# Spring properties
spring:
  application:
    name: accounts-service
  datasource:
    url: jdbc:mysql://localhost:3306/training_portal
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
      hibernate:
        ddl-auto: update
        show-sql: true

# HTTP Server
server:
  port: 2222   # HTTP (Tomca-t) port