spring:
  profiles:
    active: dev
  application:
    name: accounts-service
  cloud:
    config:
      enabled: true
      import-check:
        enabled: false
      uri: "http://localhost:8888"

test:
  param1: Pooja
  param2: Thesia
