# Spring properties
spring:
  application:
    name: accounts-service
  datasource:
    url: jdbc:h2:mem:accounts
    driverClassName: org.h2.Driver
    username: root
    password: root
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
# Discovery Server Access

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port